### PR TITLE
Developer Portal

### PR DESCRIPTION
**Pull request by wilwade**
Feature Branch for the Developer Portal

Closes: #93

### CODE REVIEW

**Comment by shannonwells** [comment]
This is very hard to read - needs moar whitespace, i.e. paragraph margins:

Screenshot 2024-11-18 at 2 10 46 PM

**Comment by shannonwells** [comment]
Spacing between what looks like should be paragraphs or bullet points seems to generally be a problem:

Screenshot 2024-11-18 at 2 18 49 PM

**Comment by JoeCap08055** [comment]
This from the "Become a Provider" page doesn't look right; not sure what the design looks like but:

* Heading doesn't read like a heading. A colon might help, but still reads weird to me.
* Items beneath the heading need more separation, they run together & are hard to read. Should be bullets or offset somehow.

image

**Comment by JoeCap08055** [comment]
There doesn't appear to be any difference between nested levels of headings; ie "How You Can Become a Provider" is the main heading of a series of steps, but the steps have the same size & appearance as the parent.

image

**Comment by JoeCap08055** [comment]
Clicking the same item in the sidebar multiple times gets the 404 page every other time

**Comment by JoeCap08055** [comment]
In general, more white space is needed to break up long content paragraphs.

**Comment by saraswatpuneet** [comment]
Clicking on sidebar item more than once seems to append page url to base , keeping clicking and notice the address bar

**Comment by mattheworris** [comment]
> In general, more white space is needed to break up long content paragraphs.

Agreed. I can make a list of pages with whitespace issues, if that's helpful.

**Review by claireolmstead — APPROVED** [review]
🚢

**Pull request merged**
